version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "03:00"  
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "VaheAA"
